### ISSUE TITLE
Enhanced Shaman's Mastery, It seems to be unable to display normally.

### ISSUE THREAD

**Issue by BlueNightSky** [mestar99/TrueStatValues#2]
My 70 Level Enhanced Shaman be unable to display Mastery. But other Stats is work.

**Comment by mestar99** [comment]
I just put a fix in for the 11.0.2 update which fixed the GetSpellInfo and gsub errors which were causing Mastery to not be displayed. It should be working with v1.6

**Comment by BlueNightSky** [comment]
I installed the latest version, but the problem is still.
I heard that the shaman that my friend (level 61) is display normal, but I can't display it normally.(level 70) I don't know why？

**Comment by mestar99** [comment]
> I installed the latest version, but the problem is still. I heard that the shaman that my friend (level 61) is display normal, but I can't display it normally.(level 70) I don't know why？

Are you getting an error or can you post a screenshot? I just checked on my lvl 70 Enhancement Shaman and it's displaying correctly for me

**Comment by BlueNightSky** [comment]
<img width="431" alt="TCS" src="https://github.com/user-attachments/assets/bff4c499-1b25-4bd8-857e-5b0c79d626ad">
The left is Haste, normal display, and the right is Mastery.

**Comment by mestar99** [comment]
Ah ok - I wonder if its something with the locale that is making it not work for mastery? I will try and see if I can reproduce it locally. Are you using the zhCN locale?

**Comment by BlueNightSky** [comment]
No, is zhTW (Traditional Chinese - Taiwan)

**Comment by mestar99** [comment]
Is that the full tooltip that you sent in the picture? I believe the first line should contain something like "精通：强化元素" and the addon finding that text is what identifies it as the Mastery tooltip and adds the True Rating / Lost Rating / Progress Bar. If it isn't found, it wouldn't display the info

This screenshot is from the Live WoW Client (11.0.2.56110) right?

I might have also figured out how to have the addon tie directly into the paperdoll frame instead of scanning tooltips so that might fix the issue once it is implemented. That will involve rewriting some of the addon though to remove the tooltip scanning

**Comment by BlueNightSky** [comment]
Very strange, a friend uses simplified Chinese client (zhCN), it is normal, and the text that display is different from me.
![5kQ2u-184lZvT3cSvz-i5](https://github.com/user-attachments/assets/51a8484a-2eb0-4946-9c72-d46b05b8e0dd)
I did not show the colon and the text behind.
Even if I switch the talent to the element, the same: 
![WoWScrnShot_081624_191548](https://github.com/user-attachments/assets/dbcadcc0-f6e8-4bc2-b8b5-881af88ee68d)

**Comment by BlueNightSky** [comment]
I found the reason, the culprit is a WA：[https://wago.io/bRl2gJIgz](url)
After I stop the wa and RL, the display is normal.
![WoWScrnShot_081624_205026](https://github.com/user-attachments/assets/4c4fa2f3-8f2b-4b50-a02e-23581578299b)
